version: '3.8'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scraper:
    build:
      context: ./scraper
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017

  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend

volumes:
  mongo_data:
